### ISSUE TITLE
Support custom logic for shared pages

### ISSUE THREAD

**Issue by tomdyson** [cfpb/wagtail-sharing#18]
As discussed with @chosak, it would be great to be able to inject custom logic on shared pages at shared time. Our immediate use case is to include the `<script>` snippet required by https://genius.com/web-annotator, which in turn will allow us to annotate and comment on draft pages.

Alternatives to genius.com include

 - http://annotatorjs.org
 - https://web.hypothes.is
 - https://trackduck.com

This could possibly be hacked by including the snippet in `wagtailsharing/banner.html` but it would be better to have more control, e.g. over the placement of the snippet, or to support different behaviour for different page types.

**Comment by tomdyson** [comment]
Now handled by #20 - thanks @chosak!

**Comment by chosak** [comment]
Thank you @tomdyson for the suggestion. This is now available in [version 0.6 on PyPI](https://pypi.org/project/wagtail-sharing/0.6/).
