### ISSUE TITLE
Not compatible with wagtail 4

### ISSUE THREAD

**Issue by spapas** [cfpb/wagtail-sharing#57]
Please fix setup.py `install_requirements` so this package will be compatible with wagtail 4.

**Comment by spapas** [comment]
Hello friends, Wagtail 4.2 is out and this issue is *still* open. 

The setup.py hasn't been fixed yet: https://github.com/cfpb/wagtail-sharing/blob/main/setup.py#L5

I am using my branch that has only this setup.py change for almost 6 months without problems (https://github.com/cfpb/wagtail-sharing/compare/main...spapas:wagtail-sharing:main)

Should we consider this Is this package deprecated ? 

Thank you

**Comment by chosak** [comment]
Support for versions of Wagtail up through 4.2 has now been added in #62.
