### ISSUE TITLE
Suggested change to banner text

### ISSUE THREAD

**Issue by schaferjh** [cfpb/wagtail-sharing#6]
I'd like to discuss the wording/purpose of the banner atop shared pages.

Given that Wagtail has a "preview" function that is different than this sharing function, I think the usage of the word "preview" may be confusing. Also, given that a user viewing the banner is on internal domain, warning them that the content may not match the published state of the page almost seems alarming in the wrong way -- they probably didn't expect it to match the published state.

## Current behavior
Pages viewed on the internal sharing sever include the banner "Preview: This content may not represent the published state of this page."

## Suggested behavior
This should probably be discussed further depending on the intent of the banner. I also suggest directly addressing the user. Some initial thoughts:

**Purpose:** 
To reassure users that the content they are seeing (which may be "draft") is not viewable by the public.
**Text:**
"Internal only: This page is only viewable within our system."

**Purpose:** 
To remind users that things may look different from the live site because they are on the share domain not the live domain.
**Text:**
"Reminder: You are viewing our staging site. Content may differ from our live site."

**Purpose:**
To remind users not to share these links with outside users to avoid errors.
**Text:**
"Warning: Please do not distribute staged pages outside our system."

**Comment by chosak** [comment]
@schaferjh thanks for the thoughtful writeup. I like all of your suggestions. I prefer the second option, with a minor change from "staging" to "sharing" to be more consistent with how we refer to this repository and how it is used.

I've opened PR #8 to make this change, and here's what the banner looks like:

![image](https://cloud.githubusercontent.com/assets/654645/23217785/64e78866-f8e8-11e6-8f03-859769815edc.png)

What do you think?

**Comment by schaferjh** [comment]
I like it!

**Comment by chosak** [comment]
PR #8 merged. Thanks for the feedback @schaferjh!
