### ISSUE TITLE
Conflicting migrations error in tox tests

### ISSUE THREAD

**Issue by nickmoreton** [cfpb/wagtail-sharing#66]
Short description explaining the high-level reason for the new issue.

## Current behavior

On a forked repo when running `tox` the tests fail when installing Wagtail>=4.2<4.3
My testing branch is your main branch.

Your tests all passed the last time they ran but I can see that Wagtail only had `4.2.3` as the latest at that point.
https://github.com/cfpb/wagtail-sharing/actions/runs/4959075722/job/13434905835#step:5:15

I'm not convinced this is an issue with your package but may be an upstream issue for Wagtail v4.2.4

## Expected behavior

Tests should pass

## Steps to replicate behavior (include URLs)

To narrow this down I altered the tox file to have:

```
envlist=
    lint,
    python{3.8}-django{3.2}-wagtail{3.0},
    python{3.8,3.11}-django{3.2,4.1}-wagtail{4.1,4.2,4.2.3,4.2.4},
    coverage
...
deps=
    django3.2: Django>=3.2,<3.3
    django4.1: Django>=4.1,<4.2
    wagtail3.0: wagtail>=3.0,<4.0
    wagtail4.1: wagtail>=4.1,<4.2
    wagtail4.2: wagtail==4.2
    wagtail4.2.3: wagtail>=4.2.3,<4.2.4
    wagtail4.2.4: wagtail==4.2.4
```
and ran

`tox -e python3.11-django4.1-wagtail4.2` (passes)
`tox -e python3.11-django3.2-wagtail4.2.3` (passes)
`tox -e python3.11-django4.1-wagtail4.2.4` (fails)

The failure is:

```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0013_fullfeaturedsnippet, 0019_fullfeaturedsnippet_translatable in tests).
To fix them run 'python manage.py makemigrations --merge'
```

My CI failiure: https://github.com/torchbox-forks/wagtail-sharing/actions/runs/5693687383

**Comment by nickmoreton** [comment]
I raised the issue here: https://github.com/wagtail/wagtail/issues/10724

**Comment by chosak** [comment]
Thanks @nickmoreton; I commented over on https://github.com/wagtail/wagtail/issues/10724#issuecomment-1666123448 but I agree it looks like an upstream issue with 4.2.4.

**Comment by chosak** [comment]
I've opened https://github.com/cfpb/wagtail-sharing/pull/68 to deprecate reliance on Wagtail's testapp.
